---
- connection: local
  hosts: localhost
  gather_facts: false
  vars_files:
  - ../vars/shared_vars.yml
  tasks:
  - name: Obtain Version of Controller
    avi_api_version:
      avi_credentials: "{{ avi_credentials }}"
    register: avi_version
  - set_fact:
      avi_credentials: "{{ avi_credentials | combine ({'api_version': avi_version['obj']['version']}) }}"
  - name: Collect Version Related Tasks
    command: "ls version_checks"
    register: ver_dir
  - avi_tenant:
      avi_credentials: "{{ avi_credentials }}"
      name: "{{ tenant_name }}"
      config_settings:
          se_in_provider_context: true
          tenant_access_to_provider_se: true
          tenant_vrf: false
    loop: "{{ module_names }}"
    loop_control:
      loop_var: tenant_name
    name: Create or Update Tenants
  - name: Cleanup
    include_role:
      name: avinetworks.aviconfig
    vars:
      avi_config_state: absent
      avi_config_file: "{{ module_name }}.yml"
    loop: "{{ module_names }}"
    loop_control:
      loop_var: module_name
  - name: Run Version Related Tasks
    vars:
      object_state: absent
    include: "{{ 'version_checks/' + item }}"
    with_items: "{{ ver_dir.stdout_lines }}"
    when: ver_dir
  - name: Run Version Related Tasks
    include: "{{ 'version_checks/' + item }}"
    with_items: "{{ ver_dir.stdout_lines }}"
    when: ver_dir
  - name: Setup module04
    include_role:
      name: avinetworks.aviconfig
    vars:
      avi_config_file: "{{ module_name }}.yml"
    loop: "{{ module_names }}"
    loop_control:
      loop_var: module_name
  - name: Current VS Count
    avi_api_session:
      avi_credentials: "{{ avi_credentials }}"
      tenant: "*"
      http_method: get
      path: virtualservice
      params:
          fields: name
    register: vs_collect
  - name: SEG VS Capacity Update
    avi_serviceenginegroup:
        avi_credentials: "{{ avi_credentials }}"
        avi_api_patch_op: replace
        avi_api_update_method: patch
        max_vs_per_se: "{{ vs_collect['obj']['count'] }}"
        name: Default-Group
        tenant_ref: /api/tenant/?name=admin
        tenant: admin
        cloud_ref: '/api/cloud/?name=Default-Cloud'
  - name: Setup module04-12
    include_role:
      name: avinetworks.aviconfig
    vars:
      avi_config_file: "{{ module_name }}"
    loop:
      - "module04-12.yml"
    loop_control:
      loop_var: module_name